# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true


# Setup
title:               Koledy
tagline:             '.suki.wtf'
description:         'Koledy jednoduše'
url:                 https://koledy.suki.wtf
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jakub Boukal
  url:               https://github.com/SukiCZ
  email:             www.bagr@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             0.1.0
google_analytics_id: #UA-XXXX-Y
